### ISSUE TITLE
[Request] .env.* file icons

### ISSUE THREAD

**Issue by denis-peshkov** [vscode-icons/vscode-icons#1566] opened 2018-04-30 04:36 UTC
Hi guys, how about standard icons for env?
I found out that you parse only *.env but how about *.env*, i.e. in react apps I have next list of env files:
.env.development
.env.production
.env.test
.env.development.local

Could you add it pls?

**Comment by jens1o** [comment] 2018-04-30 07:34
duplicate of https://github.com/vscode-icons/vscode-icons/issues/1563

**Closed by jens1o** 2018-04-30 07:34 UTC
