### ISSUE TITLE
[Icon Request]: XAML Icon

### ISSUE THREAD

**Issue by gmcoates101** [vscode-icons/vscode-icons#3595] opened 2024-09-25 09:15 UTC
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Icon Type

- [X] File Icon
- [ ] Folder Icon

### Icon Type

- [X] Extension
- [ ] Filename
- [ ] Language ID

### Original Icon

![xaml copy](https://github.com/user-attachments/assets/e1134d8d-71b4-46f1-bbfd-0a1ed5c81e40)

### Icon Information

XAML markup file for .NET Maui

**Comment by remcohaszing** [comment] 2024-12-02 14:58
Duplicate of #3465

**Closed by remcohaszing** 2024-12-02 14:58 UTC
