### ISSUE TITLE
vscode-icons extension memory leak

### ISSUE THREAD

**Issue by guglielmomoretti** [vscode-icons/vscode-icons#1787] opened 2018-11-23 16:22 UTC
- [X] I'm sure this issue is not a _duplicate_.
- More info:

I'm experiencing memory issues with vscode.  A process, namely /usr/share/code /usr/share/code/resources/app/out/out/bootstrap-fork --type=searchService is  eating memory (up to 35GB of RAM in my Workstation). I found that uninstalling/disabling vscode-icons extensions solves the issue.

**Comment by robertohuertasm** [comment] 2018-11-23 18:52
Can you provide us with:

- information about your OS
- information about your VSCode version
- if you disable all the extensions but `vscode-icons`, is this still happening? this would be very useful to identify if this leak is caused due to a combination of processes.

**Comment by guglielmomoretti** [comment] 2018-11-26 08:15
- OS Info

> ➜  ~ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
➜  ~ uname -a
Linux gmorettipc 4.15.0-39-generic #42~16.04.1-Ubuntu SMP Wed Oct 24 17:09:54 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- VS info

> Version: 1.29.1
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:07:43.495Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

- if you disable all the extensions but vscode-icons, is this still happening? this would be very useful to identify if this leak is caused due to a combination of processes

Yes, it happens. I disabled every extension but vscode-icons and that process is still heating RAM. Around 1GB per second. Please find attacched the screenshot with all the vscode processes.

**With** vscode-icons

![image](https://user-images.githubusercontent.com/2829667/49000899-46fb6a80-f15b-11e8-9471-1d6ab87c456b.png)

**Without** vscode-icons

![image](https://user-images.githubusercontent.com/2829667/49000966-85912500-f15b-11e8-8a9f-6055acf3cd56.png)

N.B.: Please note that the project I'm working on is a yocto-based project and thus it contains thousands of file.

Hope you have enough information.
Regards

**Comment by JimiC** [comment] 2018-11-30 14:04
@guglielmomoretti Hi. Sorry for taking so long to respond. Unfortunately, I and @robertohuertasm are kinda busy with our works and the development of the extension has slowed down

To the point, I suspect that your issue may have to do with the event listener we are using to monitor changes in the settings. What we aren't doing, is properly disposing the listener and thus this may introduce the memory leak. This thought has been taken care of in the `v8` version but I have no idea when Roberto will find some time to finish the code review. So there is no ETA when this will probably get fixed for you.

**Comment by guglielmomoretti** [comment] 2018-12-03 08:30
Thanks for the response.

Glad you kinda know where the issue is.
Unfortunately the only solution for me is to uninstall the extension, so a pretty bad solution actually.

Do you know why it seems I'm the only one who's having this issue? In my case it is very reproducibile, every time I start vscode actually.

Thanks
Best Regards

**Comment by JimiC** [comment] 2018-12-03 11:09
The issue should be noticeable in case an extension triggers a lot of config changes. I'm only speculating that is the case cause I've seen it happen with other projects. In order to have a confirmation, we will have to reproduce the issue ourselves. If you happen to know of a project that we can access, so to have a reproduction of the issue, it would be very helpful.

**Comment by guglielmomoretti** [comment] 2018-12-04 08:08
I'm not allowed to upload the project. But it is a Yocto based project with thousands and thousands of different files. Every project build recreates and/or modifies lots of these files.

Of course it is enough to say that the memory leak does not happen with smaller projects.

I hope this can help somehow.

**Comment by robertohuertasm** [comment] 2018-12-08 17:43
Hopefully, we'll be releasing v8 today or tomorrow. 😃

**Comment by JimiC** [comment] 2018-12-16 16:57
We have released `v8`. Awaiting your comments.

**Comment by JimiC** [comment] 2018-12-18 10:52
Judging by the provided SS the problem doesn't seem to be related with our extension after all. Since the offending process is not the `extensioHost`, the problem lies with `vscode` itself and looking at the `-type` I would say that the `searchService` is to blame. If it's not much to ask, drop by their repo and have a [look](https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+in%3Abody+searchService+)  if any reported issue relates.

**Comment by JimiC** [comment] 2018-12-18 10:54
Looking again at the original SS without our extension the `searchService` doesn't kick in.

**Comment by guglielmomoretti** [comment] 2018-12-18 11:49
@JimiC Yes, the offending process is run only when vscode-icons is enabled.

**Comment by JimiC** [comment] 2018-12-18 14:08
You need to ask the `vscode` team what is the logic behind icon themes and the `searchService` and why it consumes so much RAM for `Yocto` projects.

**Comment by guglielmomoretti** [comment] 2018-12-18 20:30
Yes, I could also do it. But please keep in mind that this only happens in combination with the vscode-icons extension. I used to have more than twelve extension enabled before running into this issue. After disabling vsicons the problem disappeared. So maybe it's just your extension that reveals a vscode bug. I'm pretty sure that if I report this issue to the vscode they'll redirect me to you again. But I'll try and let you know. Thanks for your support!

**Comment by JimiC** [comment] 2018-12-18 20:42
Surely, it has something to do with icons and I'm wondering if this happens with other icon theme extensions. The main difference of our extension with others is that we use `svg` icons which may be the fundamental cause of the issue. Now if you could point me to an OSS Yocto project, that shows similar behavior with your I could investigate further and if it's indeed a `vscode` bug I could help the team resolve it.

**Comment by JimiC** [comment] 2019-02-03 14:37
@guglielmomoretti Any new input on the issue? Should I close it?

**Comment by guglielmomoretti** [comment] 2019-02-03 17:40
I'm sorry but I didn't have time to proceed the investigation... I'll try
to give you a yocto project asap.

Best regards

Il giorno Dom 3 Feb 2019, 15:37 Jimi (Dimitris) Charalampidis <
notifications@github.com> ha scritto:

**Comment by JimiC** [comment] 2019-04-05 11:21
@guglielmomoretti I'm pondering for a while now on this issue and the only logical explanation I can come up is that this issue has to do with our call to `vscode` `findFiles` function that uses the `searchService`.

Try using `vsicons.projectDetection.disableDetect: true` in your project's workspace settings (the `setting.json` file in the `.vscode` folder) and observe its behavior.

Awaiting your response.

**Comment by KingDarBoja** [comment] 2020-09-19 00:28
This issue is too old already, if the author doesn't respond before October 2020, I am going to close this one for housekeeping purposes. Cheers! 🚀

**Comment by robertohuertasm** [comment] 2021-01-03 10:26
See previous comment.

**Closed by robertohuertasm** 2021-01-03 10:26 UTC
Labels: needs more info
