### ISSUE TITLE
it always display the active information when restart vscode

### ISSUE THREAD

**Issue by xuyae573** [vscode-icons/vscode-icons#1104] opened 2017-07-28 03:47 UTC
After I install this theme and I have already set it as file icon theme, but it always display the information for active purpose. how to solve?

![image](https://user-images.githubusercontent.com/1418798/28701703-8c404f66-738a-11e7-92a6-4d9df6d39117.png)

**Comment by robertohuertasm** [comment] 2017-07-28 07:54
Duplicate of #1098 and #1100.

Download the latest version of the extension (`7.12.0`). It should be fixed.

**Closed by robertohuertasm** 2017-07-28 07:54 UTC
Labels: duplicate

**Comment by theSoenke** [comment] 2017-08-01 18:42
I'm on version 7.12.0 but I'm still seeing it every time i open vscode

**Comment by jens1o** [comment] 2017-08-01 19:34
I'm sorry, but I can't reproduce anymore. Can you @robertohuertasm @JimiC ?

**Comment by JimiC** [comment] 2017-08-01 20:25
It shouldn't be possible. Even if you close `vscode` without pressing any button the message doesn't show up.
We'll need exact reproduction steps to investigate further.

**Comment by theSoenke** [comment] 2017-08-01 20:46
I can recreate this every time i open vscode

OS: Solus
vscode: 1.14.2 built with node 7.4.0
System node: 8.2.1

I also checked the developer console and saw this error. 

```
/usr/share/vscode/resources/app/out/vs/workbench/electron-browser/workbench.main.js:196546 [Extension Host] Activating extension `robertohuertasm.vscode-icons` failed: ENOENT: no such file or directory, open '/home/soenke/.config/Code/User/vsicons.settings.json'.
ExtensionHostProcessWorker.logExtensionHostMessage @ /usr/share/vscode/resources/app/out/vs/workbench/electron-browser/workbench.main.js:196546
/usr/share/vscode/resources/app/out/vs/workbench/electron-browser/workbench.main.js:196546 [Extension Host] Activating extension `robertohuertasm.vscode-icons` failed:  ENOENT: no such file or directory, open '/home/soenke/.config/Code/User/vsicons.settings.json'
```

Looks like it can't find vsicons.settings.json. vscode stores all settings in `$HOME/.config/Code\ -\ OSS` for me

**Comment by JimiC** [comment] 2017-08-01 20:58
`vscode` only stores in `Code - OSS` if you use a self-build instance. Is that your case?

**Comment by theSoenke** [comment] 2017-08-01 21:07
No, i use the official package for my distro. But i could reach out to the maintainer so this can be fixed. This are the build steps https://dev.solus-project.com/source/vscode/browse/master/package.yml Do you know whether there is any parameter to set to change the config directory during the build?

**Comment by JimiC** [comment] 2017-08-01 21:15
In `7.12.0` we added support for `Code - OSS` versions as well. Normally the path where `vsicons.settings.json` is placed should be `$HOME/.config/Code - OSS/User`. The path you mention in your comment is suspicious.
Unfortunately, I don't possess any knowledge on building `vscode` instances.

**Comment by theSoenke** [comment] 2017-08-01 21:40
Thanks for your help. For now i use an alias to `code-oss --user-data-dir /home/soenke/.config/Code`
