### ISSUE TITLE
Generic folder icons not displaying

### ISSUE THREAD

**Issue by daleecc** [vscode-icons/vscode-icons#924] opened 2017-05-11 15:05 UTC
The icons for generic folders are not displaying after the latest update (7.7.0). See screenshot below:

![vscode-icons](https://cloud.githubusercontent.com/assets/26437536/25956407/8d3d7434-3663-11e7-9bf7-ccd9fcc638b0.png)

**Comment by robertohuertasm** [comment] 2017-05-11 15:24
F1 > Icons: Apply Icons Customization

**Comment by daleecc** [comment] 2017-05-11 15:28
@robertohuertasm No effect unfortunately. The icons are still missing.

I'm getting this error in the dev tools:

![vscode-icons](https://cloud.githubusercontent.com/assets/26437536/25957638/b53528b2-3666-11e7-90a6-867c9e7b1512.png)

Same for default_folder_opened.svg

**Comment by jens1o** [comment] 2017-05-11 15:30
It seems that the installation is somehow incomplete. @robertohuertasm Do you removed some files inside your dist folder?

**Comment by robertohuertasm** [comment] 2017-05-11 15:30
nope, it should be working. Try to reinstall the extension. You should have these icons there.

**Comment by daleecc** [comment] 2017-05-11 15:34
@robertohuertasm Looks like all of the default_*.svg files are missing. I tried reinstalling and the default_folder.svg file showed up but the other two didn't. I reinstalled again and all 3 are missing again.

**Comment by robertohuertasm** [comment] 2017-05-11 15:39
I can assure you that the icons are there in the released package. I've just tested it and reinstalled the extension and it works. Why you have such a weird behavior? I don't know... Because you said that one time you were able to download one svg but then again none of them...

Have many icons do you have in the folder? You should have 420. Obviously you will have 3 less, but I'm wondering if this is affecting just default icons.

**Comment by daleecc** [comment] 2017-05-11 15:44
Only 413. File list attached.

[FileList.txt](https://github.com/vscode-icons/vscode-icons/files/993588/FileList.txt)

**Comment by robertohuertasm** [comment] 2017-05-11 15:52
When you uninstall the extension, can you look if the folder is still there? or is it completely removed? Do you have any antivirus? Can you disable it?

**Comment by daleecc** [comment] 2017-05-11 15:54
Yes the extension folder disappears when I uninstall the extension. I have antivirus but cannot disable it. It was working before the latest update.

**Comment by robertohuertasm** [comment] 2017-05-11 15:57
The thing is that this was not changed. And the release shouldn't be affecting the icons which are already packaged in the extension. It seems that there's something preventing some of the icons to get stored in your hard drive but I cannot determine why.

Why is that you cannot disable the antivirus? Are you in a company PC? It's that's the case, do you have any other colleagues suffering the same issue?

**Comment by HuangStomach** [comment] 2017-05-12 02:03
I have the same problem after I update it to 7.7.0
but when I reinstall the extension, it was solved

**Comment by Bigdragon13th** [comment] 2017-05-12 05:50
Happened to me too on 7.7.0
Reinstall fixed the issue.

**Comment by daleecc** [comment] 2017-05-12 09:33
Yes it's a company PC so the antivirus settings are locked. I checked with a colleague and they did not have the same issue during the upgrade.

**Comment by robertohuertasm** [comment] 2017-05-12 10:46
This is very weird. I don't know how to tackle it. A colleague of mine has reported me the same issue.
The thing is that the icons are there in the released package. That's why they're being found upon reinstallation. 

I'm not aware of any process that we may have introduced that could cause icon deletion. I'll check it out just in case.

For me, this all seems a failure in the distribution process which is not controlled by us. But still not sure of it.

**Comment by jens1o** [comment] 2017-05-12 12:06
@robertohuertasm Maybe you can make the vsix public, maybe this package is not broken?

**Comment by JimiC** [comment] 2017-05-13 11:29
I've seen this happening on my machine as well but if I uninstall and re-install the extension all is fine. I'm too baffled on why this is happening.

**Comment by jens1o** [comment] 2017-05-13 11:38
Raise an issue at vscode's repo?

**Comment by JimiC** [comment] 2017-05-13 11:53
@jens1o I just tested it several times and in some random cases, I managed to reproduce it. It seems as this is a CDN issue.

Notice in screenshot that several icons are missing.

![screenshot - 13_05_2017 14_53_14](https://cloud.githubusercontent.com/assets/1716442/26025241/ecab2f7c-37eb-11e7-93c3-bc27f5c90a86.png)

**Comment by jens1o** [comment] 2017-05-13 11:55
But the cdn is not controlled by us. I think we should raise an issue at vscode's repo.

**Comment by robertohuertasm** [comment] 2017-05-13 14:40
@jens1o, it's a good idea. Probably this issue is already affecting other extensions although I haven't found any issue related to this specific matter in their Github.

I've checked out the content of the `vsix` [package being downloaded from the CDN](https://robertohuertasm.gallerycdn.vsassets.io/extensions/robertohuertasm/vscode-icons/7.7.0/1494347886279/Microsoft.VisualStudio.Services.VSIXPackage) and all the icons are present.

I don't know how, the package may have been badly distributed by Microsoft CDN and that's why some people seem to be missing some of the icons and/or maybe other files. Hopefully, this may have been some occasional and random issue.

**Comment by jens1o** [comment] 2017-05-13 14:48
I'll do it as soon as my English is good again. 😆

**Comment by JimiC** [comment] 2017-05-13 15:20
The thing is that I noticed this behavior when `1.12` was still as `insiders`. I didn't notice it on `1.11`. So it may not be a CDN issue but something in the code that deflates the `vsix` file. I'm wild guessing here so I'm not sure if we should notify the `vscode` team.

**Comment by jens1o** [comment] 2017-05-13 15:23
Why not? How they should fix the problem without getting feedback about it? By randomness?

**Comment by JimiC** [comment] 2017-05-13 15:25
@jens1o Can you provide them reproduction steps? A bug report is as good as the info (repro steps) the reporter provides.

**Comment by jens1o** [comment] 2017-05-13 15:50
How can I provide reproduction steps when it depends on luck to get this?

**Comment by JimiC** [comment] 2017-05-13 17:03
Now you get my point.

**Comment by jens1o** [comment] 2017-05-13 19:18
Did I forgot mention anything?

**Comment by daleecc** [comment] 2017-05-18 12:09
I've updated VSCode to 1.12.2, uninstalled the extension, reloaded the window and then re-installed the extension. I've got all icons except default_file.svg so I guess I'll just copy that in place for now.

**Comment by JimiC** [comment] 2017-05-19 11:17
Closing. Please see https://github.com/Microsoft/vscode/issues/26602#issuecomment-302640992

**Closed by JimiC** 2017-05-19 11:17 UTC
Labels: bug, vscode official integration
