### ISSUE TITLE
Missing folder icons

### ISSUE THREAD

**Issue by ventayol** [vscode-icons/vscode-icons#1009] opened 2017-06-07 12:53 UTC
With the last update, I'm missing folder icons.

You can see the screenshot here:
![screen shot 2017-06-07 at 14 52 16](https://user-images.githubusercontent.com/1505998/26879345-0b0e0490-4b91-11e7-884e-9678ac28c945.png)

**Comment by jens1o** [comment] 2017-06-07 12:54
This is a `vscode` bug which will be fixed with next release.

**Closed by jens1o** 2017-06-07 12:54 UTC
Labels: duplicate

**Comment by jens1o** [comment] 2017-06-07 12:55
Duplicate of #989 and #924

**Comment by ventayol** [comment] 2017-06-07 14:20
Ahh, nice.
The reinstall worked!

And sorry for the duplicate, I did a quick search and I didn't find the other ones.
