### ISSUE TITLE
Icon for *.scss file not showing

### ISSUE THREAD

**Issue by YeaseonZhang** [vscode-icons/vscode-icons#808] opened 2017-03-13 08:00 UTC
**vscode-icons** 7.3.0 

- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request(if not, remove these lines below):
      - Type: [extension/folder]
      - Icon Name: [scss]
![e0e6jppi8 01 d8z0e](https://cloud.githubusercontent.com/assets/17896253/23845966/17b95e84-0806-11e7-84e3-65d0a3270947.png)

**Comment by JimiC** [comment] 2017-03-13 08:42
Can't reproduce. Works for me on `Code` and `Code-Insiders`.
Please post what extensions you use.

**Comment by YeaseonZhang** [comment] 2017-03-14 02:42
@JimiC  **Win10  Code-insider (1.11.0)** and **Ubuntu 15.10 Code-insider (1.11.0)**  can't show .scss icon，but **vscode** can show .scss icon

**Comment by jens1o** [comment] 2017-03-14 05:25
@YeaseonZhang Please give us a list of your extensions. You can do that by clicking on `Help > Report Issues` and copy the extension list from the issue created by vscode.

**Comment by YeaseonZhang** [comment] 2017-03-14 05:29
- VSCode Version: Code - Insiders 1.11.0-insider (dd197f19ddad6f8fa960c5f330fb7182c2321de3, 2017-03-13T07:11:52.101Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|project-manager|alefragnani|0.13.4|
|vscode-eslint|dbaeumer|1.2.7|
|githistory|donjayamanne|0.2.0|
|vscode-babel-coloring|dzannotti|0.0.4|
|vscode-html-css|ecmel|0.0.33|
|EditorConfig|EditorConfig|0.6.2|
|vscode-npm-script|eg2|0.1.8|
|code-runner|formulahendry|0.6.14|
|terminal|formulahendry|0.0.7|
|vue-snippets|hollowtree|0.1.1|
|beautify|HookyQR|1.0.1|
|Angular2|johnpapa|2.0.3|
|vscode-codemetrics|kisstkondoros|1.2.0|
|vue|liuji-jim|0.1.5|
|markdown-shortcuts|mdickin|0.7.1|
|PowerShell|ms-vscode|0.9.0|
|debugger-for-chrome|msjsdiag|2.6.0|
|debugger-for-edge|msjsdiag|0.4.1|
|vetur|octref|0.5.1|
|vscode-icons|robertohuertasm|7.3.0|
|sass-indented|robinbentley|1.3.0|
|vue|seanwash|0.4.2|
|Angular2|UVBrain|0.4.1|
|vim|vscodevim|0.6.5|
|JavaScriptSnippets|xabikos|1.4.0|
|Material-theme|zhuangtongfa|2.2.4|;


---
@jens1o There is my extensions

**Comment by JimiC** [comment] 2017-03-14 11:17
Extension `sass-indented` is causing the issue. It's not entirely the extensions fault.
You see `vscode` has a strange declaration at https://github.com/Microsoft/vscode/blob/master/extensions/scss/package.json#L12.
You may want to address your issue there.

**Comment by JimiC** [comment] 2017-03-15 16:46
Closing this as it's a `sass-indended` issue.

**Closed by JimiC** 2017-03-15 16:46 UTC
Labels: bug, vscode official integration
