### ISSUE TITLE
Causes some projects to constantly reload 

### ISSUE THREAD

**Issue by elSuperRiton** [vscode-icons/vscode-icons#1925] opened 2019-03-25 11:01 UTC
Since I've updated to last version of VScode ( 1.32.3 ) some of my projects reload indefinitely when having this plugin installed. I cannot really spot why only some projects are affected but removing extensions one by one allowed me to confirm that this plugin is the source of the issue.

**Comment by robertohuertasm** [comment] 2019-03-25 11:05
Have you tried reinstalling the extension? We changed the publisher id a few weeks ago and maybe this is affecting you. Let us know.

**Comment by JimiC** [comment] 2019-03-25 12:02
Can you please post the `vsicons` settings in your `settings.json` also?

**Comment by gjungb** [comment] 2019-03-25 15:42
I can confirm this behaviour. Reinstalling did not solve the issue.

**Comment by JimiC** [comment] 2019-03-25 15:44
@gjungb Confirming doesn't help us much. Please, provide useful info.

**Comment by ruohomaa** [comment] 2019-03-25 15:50
I have same problem, here are my vsicons settings in setting.json
`    "vsicons.projectDetection.autoReload": true,
    "vsicons.dontShowNewVersionMessage": true
`

**Comment by JimiC** [comment] 2019-03-25 15:52
@ruohomaa Change `vsicons.projectDetection.autoReload` to `false` and observe what messages pop up from the extension. Let us know the details.

**Comment by ruohomaa** [comment] 2019-03-25 15:56
Here you go:
![image](https://user-images.githubusercontent.com/6224875/54934420-284d8a80-4f27-11e9-9f21-5ebfe749b176.png)
![image](https://user-images.githubusercontent.com/6224875/54934466-38fe0080-4f27-11e9-8a28-80e01326f85a.png)

**Comment by gjungb** [comment] 2019-03-25 15:57
@JimiC here we go:
- `"vsicons.projectDetection.autoReload": true,`
- When setting it to `false` the reloading stops
- I'm working in a VS Code workbench with a mixture of Angular an NestJS

**Comment by JimiC** [comment] 2019-03-25 15:59
@ruohomaa That's what I suspected.
@gjungb Ahh, now we are getting somewhere.

I'll investigate further and hopefully come back at you all with a fix.

**Comment by JimiC** [comment] 2019-03-25 16:02
Until we fix it, use `Disable Detection` for now.

**Comment by JimiC** [comment] 2019-03-25 16:25
OK, guys. Turns out that there is no quick fix for this issue. Having mixed `Angular` and `NestJS` projects in a workbench, confuses our project detection logic. You can have either `Angular` icons or `NestJS` icons.
The only solution I can think of is to deactivate the detection and manually select which icons to enable from the `F1 > Icons: Toggle * Preset` menu.

**Comment by gjungb** [comment] 2019-03-25 16:25
@JimiC Thx, that's fine for me.

**Comment by JimiC** [comment] 2019-03-25 16:30
@robertohuertasm We will have to implement an additional step in PAD to detect such cases and present a message to the user that [s]he can only have one or the other.

**Comment by JimiC** [comment] 2019-03-31 16:57
I decided to work on resolving this issue and I figured out a way to have both icons show in a multi-project, so I decided to share it with you.

 This solution though requires you to use our custom icons configuration and declare a custom file extension.
Because there are a lot of supported file extensions setting it up is a bit tedious.

So the concept is to use a custom file name extension and declare it as such:
```
"vsicons.associations.files": [
        {
            "icon": "nest_controller_ts",
            "extensions": ["nest.controller.ts"],
            "overrides": "nest_controller_ts",
            "format": "svg"
        }
        ... // Repeat here for any other file extension you wan to support
]
```

And here is the proof:
![image](https://user-images.githubusercontent.com/1716442/55292063-d907ce00-53ee-11e9-9665-0aa0038bccb6.png)

**Closed** 2019-04-07 09:00 UTC
Labels: bug, confirmed
