### ISSUE TITLE
.github file icon reverts to standard folder icon after folder is expanded

### ISSUE THREAD

**Issue by TheRealGlumfish** [vscode-icons/vscode-icons#2601] opened 2020-08-30 02:03 UTC
- [x] I'm sure this issue is not a _duplicate_.

When I first open a folder (workspace) the .github folder has the black folder icon with the Github logo (normal). When I click to expand the folder icon changes to the opened standard folder and when I collapse the standard closed folder. Keep in mind that my .github has only one folder so VSCode shows: ".github/workflows" so this may be this issue. It is highly likely the issue is with VSCode and not with the icon theme. Thanks for making this great theme!

Edit: I could also provide screenshots if needed but I think this is pretty self explanatory and nothing visually weird is going on except from the icon swap

**Comment by JimiC** [comment] 2020-09-18 08:54
Screenshots of a `GIF` would be highly appreciated as I can't reproduce your issue.

**Comment by robertohuertasm** [comment] 2020-09-18 09:02
This seems to be related to the [compact folders](https://code.visualstudio.com/updates/v1_41#_compact-folders-in-explorer) feature. I can reproduce it when I have a subfolder in the `.github` folder.

@TheRealGlumfish It seems to me that this is a vscode issue, so I would report this into their repo referencing this issue.

![image](https://user-images.githubusercontent.com/696981/93579054-4d954a80-f99e-11ea-992d-7a6c0b123f6f.png)

![image](https://user-images.githubusercontent.com/696981/93579113-5f76ed80-f99e-11ea-8849-bedf2fa76652.png)

**Comment by robertohuertasm** [comment] 2020-09-18 09:03
@TheRealGlumfish for the moment you can disable this feature as a workaround. Not the ideal solution but you'll have your icon back.

**Comment by JimiC** [comment] 2020-09-18 09:05
Didn't even knew that option existed.

**Comment by TheRealGlumfish** [comment] 2020-09-18 18:23
> Screenshots of a `GIF` would be highly appreciated as I can't reproduce your issue.

I'll try getting that and I'll get back to you.

**Comment by JimiC** [comment] 2020-09-18 18:27
@TheRealGlumfish No need. @robertohuertasm gave you the answer.

**Comment by robertohuertasm** [comment] 2021-01-03 10:14
@TheRealGlumfish I'm closing this as this is not something we can work on. The issue is that vscode is assigning the inner folder icon to the whole set (when compact folder is on in your settings, which I think is the default).

So as a workaround we can do two things:
1. Disable the compact folder feature
1.[ Associate the inner folder name ](https://github.com/vscode-icons/vscode-icons/wiki/FineTuning)with the icon you wish to have.

**Closed by robertohuertasm** 2021-01-03 10:14 UTC
Labels: bug, vscode official integration
