### ISSUE TITLE
Not showing folder icons

### ISSUE THREAD

**Issue by Alex-Sokolov** [vscode-icons/vscode-icons#989] opened 2017-06-03 07:55 UTC
After update extension to version 7.8.1 folder icons not showed anymore.

![2017-06-03 10 54 06](https://cloud.githubusercontent.com/assets/4497128/26751804/239aacf0-484b-11e7-84be-3f2ec46fa057.png)

**Comment by jens1o** [comment] 2017-06-03 07:57
should be a duplicate of #924.

**Closed** 2017-06-03 07:58 UTC
Labels: duplicate

**Comment by JimiC** [comment] 2017-06-03 09:39
Uninstall and re-install the extension.

**Comment by Alex-Sokolov** [comment] 2017-06-04 05:47
Thanks! Reinstalling helps
