### ISSUE TITLE
Latest version causing VS Code Insiders ExtensionHost to error/crash

### ISSUE THREAD

**Issue by jtsom** [vscode-icons/vscode-icons#1128] opened 2017-08-15 14:13 UTC
**Checklist:**

- [x] I'm sure this issue is not a *duplicate*?

With this extension active, using the latest VS Code insiders (On windows 10), an error is thrown in the Developer console:

```
[Extension Host] Activating extension `robertohuertasm.vscode-icons` failed: Cannot find module 'semver'.
```
```
[Extension Host] Here is the error stack:  Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Function.G.o._load (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:403256)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\John Tsombakos\.vscode-insiders\extensions\robertohuertasm.vscode-icons-7.12.0\out\src\settings\settingsManager.js:5:16)
    at Object.<anonymous> (C:\Users\John Tsombakos\.vscode-insiders\extensions\robertohuertasm.vscode-icons-7.12.0\out\src\settings\settingsManager.js:81:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

~~~
Edited by @jens1o: We don't want full templates here ;)

**Comment by jens1o** [comment] 2017-08-15 14:45
Personally, I can't reproduce, because my extension host is destroyed at all. But before, it has worked like a charm.... I shouldn't had updated today. But also other extensions are affected, for example wix's import-cost...

**Comment by robertohuertasm** [comment] 2017-08-15 22:40
@jtsom I can't reproduce it either... I've just updated my Insiders version and installed a fresh version of `vscode-icons` and everything seems to be fine.

This is my vscode version:

![image](https://user-images.githubusercontent.com/696981/29339637-6b7de80c-821b-11e7-9cea-13682f797cf1.png)

Is this the same version as yours? Can you try reinstalling the extension?

**Comment by jtsom** [comment] 2017-08-16 10:32
Yes, that's the version I had also. It looks like it was more than just this one extension - several were having issues with the latest VS Code Insiders - Typescript Hero for one. There's an issue on the VS Code Github open about this Extension Host crash.

**Comment by robertohuertasm** [comment] 2017-08-30 22:51
I'm not sure we should be keeping this issue opened as this is completely related to some vscode bug. What do you think?

**Comment by JimiC** [comment] 2017-08-31 08:23
Closing as not related to this extension.

**Closed by JimiC** 2017-08-31 08:23 UTC
Labels: Tech Debt
