### ISSUE TITLE
The PHP icon under the vscode-icons plug-in is very ugly, can it be adjusted

### ISSUE THREAD

**Issue by linjialiang** [vscode-icons/vscode-icons#1760] opened 2018-10-26 01:29 UTC
Issue Type: <b>Feature Request</b>

> The PHP icon under the vscode-icons plug-in is very ugly, can it be adjusted

Extension version: 7.27.0
VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

**Comment by JimiC** [comment] 2018-10-26 07:29
Duplicate of #1759

**Closed by JimiC** 2018-10-26 07:29 UTC
