### ISSUE TITLE
After VSC restart I get notification

### ISSUE THREAD

**Issue by bsvipas** [vscode-icons/vscode-icons#1100] opened 2017-07-27 09:50 UTC
Hello,

I'm using latest stable VSC. Every time I get this notification even if I press "Activate".
![image](https://user-images.githubusercontent.com/30043375/28664798-38dd5c9e-72ca-11e7-96e8-0ac7779970fb.png)

**Comment by robertohuertasm** [comment] 2017-07-27 11:01
This was [reported yesterday ](https://github.com/vscode-icons/vscode-icons/issues/1097) in VSCode Insiders version and fixed in #1098. A patch will be released soon.

The thing is that this is the first time reported in VSCode (not insiders). Can you confirm the version number? 1.14.2?

**Comment by bsvipas** [comment] 2017-07-27 11:15
Yes, it's 1.14.2.

**Comment by JimiC** [comment] 2017-07-27 11:18
@robertohuertasm The issue is generic no matter the `vscode` version.

**Comment by MyBoon** [comment] 2017-07-27 21:42
Same issue for me on 1.14.2

**Comment by robertohuertasm** [comment] 2017-07-27 22:52
This has been fixed in #1098 and will be released in `7.12.0`

**Closed by robertohuertasm** 2017-07-27 22:52 UTC
Labels: duplicate
