### ISSUE TITLE
[VS Code Insiders] Issue with icons in "Open Editors" when pane is narrow

### ISSUE THREAD

**Issue by martellaj** [vscode-icons/vscode-icons#1280] opened 2017-10-20 18:51 UTC
**Bug description**
If left pane is narrow, file names cover icons. This does not happen with default icon sets that come with VS Code, so it may be an issue with your extension.

- Not a duplicate
- VS Code version: 
![image](https://user-images.githubusercontent.com/1019478/31837232-eb7f2e04-b58c-11e7-866b-88eb7c52412b.png)
- Screenshot of issue:
![image](https://user-images.githubusercontent.com/1019478/31837202-c1b10e9e-b58c-11e7-9044-c94bdc386648.png)

**Comment by robertohuertasm** [comment] 2017-10-20 20:54
I cannot reproduce it. I made the left pane very narrow and I even tried to add a file with a long path unsuccessfully. @JimiC, @jens1o, maybe you'll be luckier than me.

**Comment by JimiC** [comment] 2017-10-21 14:14
If this issue is not present on stable vscode then it's not an issue with the extension but with vscode itself.

**Comment by martellaj** [comment] 2017-10-21 14:37
I don't think it's an issue with VS Code because the default icon sets don't have this issue. I get a new Insiders build each day, so I'll report back if it gets fixed... otherwise, I'll just change the title in a couple of weeks when they fork and a new stable release goes out.

**Comment by robertohuertasm** [comment] 2017-10-21 17:32
The thing is I wasn't able to reproduce it in both stable and insiders version. Can you provide a video or animated gif of how you do it?

**Comment by JimiC** [comment] 2017-10-21 17:45
Also there is a possibility that another extension is messing with ours.

**Comment by martellaj** [comment] 2017-10-21 19:00
Here you go: https://streamable.com/a5bao

This is on my personal machine (MacBook). Original repro was on my WIndows 10 machine.

**Comment by martellaj** [comment] 2017-10-21 19:03
I also reproed the issue with all of my other extensions disabled.

**Comment by robertohuertasm** [comment] 2017-10-21 19:36
@martellaj I'll try to test in on a Mac, but I definetely can't reproduce it on my Windows machine.

![left-pane](https://user-images.githubusercontent.com/696981/31855240-a8ab664e-b6a7-11e7-9252-85c58f50f014.gif)

**Comment by robertohuertasm** [comment] 2017-10-21 19:39
@martellaj a few questions:

1. Does this happens to you in the stable version?
1. Does this happens to you to any other non-default icon set (i.e. Material Icons...)

**Comment by JimiC** [comment] 2017-10-22 15:31
Oh man this due to the new feature in insiders that shows modified file of scm.

**Comment by jens1o** [comment] 2017-10-22 18:48
I still don't see where this could be our fault. :c

**Comment by JimiC** [comment] 2017-10-22 18:59
It isn't, that's what I'm saying from the beggining.

**Comment by robertohuertasm** [comment] 2017-10-22 19:14
You're right @JimiC. It's the new `vscode` feature. See this happening with Material Icons.

![image](https://user-images.githubusercontent.com/696981/31865338-f3a4a784-b76d-11e7-871d-87faff51a668.png)

**Comment by jens1o** [comment] 2017-10-22 19:35
(didn't found some more matching labels)

**Comment by robertohuertasm** [comment] 2017-10-22 19:48
@jens1o, I would remove `bug` and `confirmed` - as this is not our bug but vscode`s - and close the issue.

**Closed** 2017-10-23 04:40 UTC
Labels: invalid, vscode official integration
