### ISSUE TITLE
CSS icon turns into folder icon

### ISSUE THREAD

**Issue by inhaq** [vscode-icons/vscode-icons#1012] opened 2017-06-08 12:04 UTC
- VSCode Version: Version 1.12.2
 - OS Version: macOS 10.12.5 (16F73)

![icon error](https://user-images.githubusercontent.com/27832433/26927557-d5da2ef8-4c6b-11e7-9349-e711a26315d2.gif)

In Explorer tab, new css files turns into folder icons after I press enter.

**Comment by JimiC** [comment] 2017-06-08 13:04
Please provide also `vscode-icons` version and a list of used extensions (can be produced from `Help > Report Issues`).

**Comment by jens1o** [comment] 2017-06-08 13:07
Is this a vscode bug? We have no influence over that? I'm trying to reproduce...

**Comment by inhaq** [comment] 2017-06-08 13:08
Version: `7.9.0 (June 6, 2017)`

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.1.1|
|html-css-class-completion|Zignd|1.6.0|
|html-snippets|abusaidm|0.1.0|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|vscode-theme-onedark|akamud|2.0.1|
|Bookmarks|alefragnani|0.15.1|
|vscode-color|anseki|0.4.1|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.4.2|
|vscode-eslint|dbaeumer|1.2.11|
|githistory|donjayamanne|0.2.0|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-babel-coloring|dzannotti|0.0.4|
|vscode-html-css|ecmel|0.1.5|
|vscode-npm-script|eg2|0.2.0|
|code-runner|formulahendry|0.6.18|
|terminal|formulahendry|0.0.8|
|live-html-previewer|hdg|0.0.1|
|rest-client|humao|0.14.4|
|hopscotch|idleberg|0.1.4|
|Angular2|johnpapa|2.3.2|
|vscode-exec-node|miramac|0.5.0|
|debugger-for-chrome|msjsdiag|3.1.2|
|vscode-icons|robertohuertasm|7.9.0|
|sass-indented|robinbentley|1.4.1|
|html5-boilerplate|sidthesloth|1.0.1|
|css-auto-prefix|sporiley|0.1.4|
|react-beautify|taichi|0.3.0|
|bootstrap4-vscode|thekalinga|2.3.3|
|JavaScriptSnippets|xabikos|1.4.0|
|ReactSnippets|xabikos|1.3.0|;

**Comment by JimiC** [comment] 2017-06-08 13:13
Damn. That's a lot of extensions to check against. From my side, I can't reproduce this issue.
@inhaq You may have to disable the other extensions one by one and observe the behavior.

**Comment by jens1o** [comment] 2017-06-08 13:14
I also cannot reproduce it. :/

**Comment by inhaq** [comment] 2017-06-08 13:14
Sorry, let me try to disable all the plugins and try it again.

**Comment by jens1o** [comment] 2017-06-08 13:17
(Except ours) ;)

**Comment by inhaq** [comment] 2017-06-08 13:21
It works fine alone. I'll check it with other plugins and update it here.

**Comment by robertohuertasm** [comment] 2017-06-09 21:29
@inhaq any news on this matter?

**Comment by inhaq** [comment] 2017-06-09 21:33
@robertohuertasm didn't find the particular scenario again and it works fine with all plugins enabled now.

**Comment by robertohuertasm** [comment] 2017-06-09 21:34
Then I'll close this. In case you can reproduce it please report back to this thread. Thanks @inhaq!

**Closed by robertohuertasm** 2017-06-09 21:34 UTC
Labels: needs more info
