### ISSUE TITLE
Activate message always shows at startup

### ISSUE THREAD

**Issue by ostrgard** [vscode-icons/vscode-icons#1178] opened 2017-09-21 16:08 UTC
- [x] I'm sure this issue is not a *duplicate*?

After upgrading to 7.13.0 i always get this message on startup:
<img width="1028" alt="screen shot 2017-09-21 at 18 01 59" src="https://user-images.githubusercontent.com/1216866/30705932-2823aaf8-9ef7-11e7-84ab-b1e5cc412671.png">

I have tried reactivating and reinstalling the extension. I have the following settings:
```
"vsicons.dontShowNewVersionMessage": true,
"vsicons.dontShowConfigManuallyChangedMessage": true
```

Thank you 😄

**Comment by JimiC** [comment] 2017-09-21 16:27
This is because you currently have active another file icon theme and `vscode-icons` installed also. For now, disable `vscode-icons` for the time you don't use it.

This issue is tracked in #1176.

**Comment by jens1o** [comment] 2017-09-21 16:36
Duplicate of #1176 

(github styling)

**Closed by jens1o** 2017-09-21 16:36 UTC
Labels: duplicate
