### ISSUE TITLE
ShellCheck support

### ISSUE THREAD

**Issue by carlocorradini** [vscode-icons/vscode-icons#2962] opened 2022-04-01 09:37 UTC
Add support for [ShellCheck](https://github.com/koalaman/shellcheck) configuration file.

- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `ico`
  - Icon Name: `shellcheck`
  - Sample original Icon:
    ![logo](https://user-images.githubusercontent.com/21266147/161237432-46f5d35b-71da-4b80-8c8d-61425783fb19.png)
  - Filenames: `.shellcheckrc`

- More info: Only `.ico` available.

**Comment by sasial-dev** [comment] 2022-04-18 22:22
Duplicate of #2881.

**Comment by carlocorradini** [comment] 2022-04-18 22:30
> Duplicate of #2881.

Right 👍

**Closed** 2022-04-18 22:30 UTC
