### ISSUE TITLE
vscode-icons is consuming a lot of CPU

### ISSUE THREAD

**Issue by samuelsonokoi** [vscode-icons/vscode-icons#1873] opened 2019-02-16 17:44 UTC
You might want to go through my console for details on this

![console-log](https://user-images.githubusercontent.com/12806939/52903212-89908880-321a-11e9-91fc-a9e48f1c2a2f.png)

**Comment by JimiC** [comment] 2019-02-16 18:11
Please provide reproduction steps.

**Comment by JimiC** [comment] 2019-02-16 18:47
We will require the `.cpuprofile.txt` to investigate further.

**Comment by JimiC** [comment] 2019-03-23 14:39
Closing due to lack of follow-up

**Closed by JimiC** 2019-03-23 14:39 UTC
Labels: needs more info
