### ISSUE TITLE
support for hidesExplorerArrows

### ISSUE THREAD

**Issue by OlivierCo** [vscode-icons/vscode-icons#1340] opened 2017-11-09 19:27 UTC
with "hidesExplorerArrows":true

[https://code.visualstudio.com/updates/v1_18#_folder-icons-in-file-icon-themes](https://code.visualstudio.com/updates/v1_18#_folder-icons-in-file-icon-themes)

<img width="763" alt="screen shot 2017-11-09 at 19 26 57" src="https://user-images.githubusercontent.com/1804322/32625373-f9c49920-c583-11e7-9c34-5750a7d2b6e0.png">

**Comment by jens1o** [comment] 2017-11-09 19:49
Duplicate of #1337

**Closed by jens1o** 2017-11-09 19:49 UTC
Labels: duplicate
