### ISSUE TITLE
Support for PCK file

### ISSUE THREAD

**Issue by Danieleeee** [vscode-icons/vscode-icons#964] opened 2017-05-29 07:40 UTC
Hi, 
relatively to the _Support for PLSQL file_ #949
We have forgotten the files with **PCK** extension (not PKG).
I use it in PLSQL as the union of Header and Body, but it's also used in other areas

**Comment by Danieleeee** [comment] 2017-05-29 07:51
The icon is the same as the files.sql.
I think it's better to use a specific one.

**Comment by jens1o** [comment] 2017-05-29 12:15
Which icon do you propose instead?

**Comment by JimiC** [comment] 2017-05-29 13:17
@Danieleeee I was thinking that you better request that the author of the `PL\SQL` extension you use includes the `pck` extension in their extension.

**Comment by JimiC** [comment] 2017-05-29 14:05
As `pck` is the combined file of `pks`, `pkh` and `pkb`, it should be supported by the extensions that implement `PL\SQL` syntax highlighting.

**Comment by Danieleeee** [comment] 2017-05-29 14:08
It is supported. 
But file icon is the same of file.sql

**Comment by JimiC** [comment] 2017-05-29 14:17
@Danieleeee If we make a specific icon for `pck` we would have to move `pks`, 'pkh' and `pkb` to that which will then conflict with the one that is used via the extension. This is unsolvable and I'm afraid you will have to live with that.

**Comment by Danieleeee** [comment] 2017-05-29 14:24
Extension don't implement icons for file.sql, pks, pkb, pck.
It implement syntax highlights for plsql code.
Are you sure that they are in conflict?

**Comment by JimiC** [comment] 2017-05-29 14:27
Yes, we depend on their extension support to trigger the icon via their 'language id' property (it's something that `vscode` itself enables).

**Comment by robertohuertasm** [comment] 2017-05-29 14:36
If my memory doesn't fail me, I think file extensions override language id. Then adding a specific icon for a concrete extension wouldn't mess at all with the `language id` support. The user should still benefit from the syntax highlighting and it will see the proper icon.

**Comment by JimiC** [comment] 2017-05-29 14:44
@jens1o Do you have a case were you can confirm @robertohuertasm saying? Cause I distinctively remember that we had a case with `html` and `vue`.

**Comment by Danieleeee** [comment] 2017-05-29 14:44
If what @robertohuertasm says is true, it would be nice to have an icon for each type of file.

**Comment by jens1o** [comment] 2017-05-29 14:47
Afaik, it's like Roberto described it. I'll check that now, but this sounds right to my memory. He wrote that some time earlier, and an user had described it like he did.

**Comment by jens1o** [comment] 2017-05-29 14:50
![image](https://cloud.githubusercontent.com/assets/11234139/26554091/d67f769a-448e-11e7-992a-e0dfc5e8c0d4.png)
At the moment, I can't reproduce that. Or does vue have included the style, so it won't fail?

**Comment by JimiC** [comment] 2017-05-29 14:51
The `vscode` team has fixed it since we brought it up.

**Comment by jens1o** [comment] 2017-05-29 14:52
Do you have the pr and issue?

**Comment by JimiC** [comment] 2017-05-29 14:52
Search our issues and you find the link.

**Comment by jens1o** [comment] 2017-05-29 14:56
For anyone searching it: https://github.com/vscode-icons/vscode-icons/issues/557#issuecomment-268033369

**Comment by JimiC** [comment] 2017-05-29 15:04
Guys, I just confirmed it and it's like I said.

Adding an icon outside the `language id` support you get the icon but no syntax highlighting simply because the file isn't associated with a language (at the bottom right it's mentioned as a `Plain Text`).
When you associate the file with the language (`PLSQL`) then the icon turns to the icon associated with the `language id`.

**Comment by JimiC** [comment] 2017-05-29 15:05
Guys, I just confirmed it and it's like I said.

Adding an icon outside the `language id` support you get the icon but no syntax highlighting simply because the file isn't associated with a language (at the bottom right it's mentioned as a `Plain Text`).
When you associate the file with the language (`PLSQL`) then the icon turns to the icon associated with the `language id`.

**Comment by JimiC** [comment] 2017-05-29 15:12
@jens1o `vscode` team fixed the issue with `html` and `vue` by removing the `vue` extension association from their inner `html` syntax highlighting extension.

**Comment by jens1o** [comment] 2017-05-29 15:13
So there is no solution for this case?

**Comment by JimiC** [comment] 2017-05-29 15:16
None that I can think of.

**Comment by robertohuertasm** [comment] 2017-05-29 21:27
@JimiC, you're right, this is working like this right now... but it shouldn't. This is a bug in `vscode`. I clearly remember talking to @aeschli about this in [vscode#10804](https://github.com/Microsoft/vscode/issues/10804#issuecomment-243403933).

From [vscode api docs](https://code.visualstudio.com/docs/extensions/themes-snippets-colorizers#_file-association):

> A file extension match is preferred over a language match, but is weaker than a file name match.

I'll suggest to keep this issue opened and open another one in vscode repo asking about this.

**Comment by JimiC** [comment] 2017-05-30 07:43
Guys, I'm terribly sorry. I must have done something wrong yesterday. `vscode` works as expected. I have some screenshots to prove it.

The following is tested in `vscode` 1.12.x and 1.13.x.

1. `PLSQL` extension is installed.
2. `pck` is assocciated with `package` icon. Icons is shown but no syntax highlighting.
>    { icon: 'pck', extensions: ['pck'], format: FileFormat.svg },

![screenshot - 30_05_2017 10_29_05](https://cloud.githubusercontent.com/assets/1716442/26572812/fdc92eea-4523-11e7-99e9-18a528e8b1be.png)

3. Associating `pck` with `PLSQL`

![screenshot - 30_05_2017 10_29_38](https://cloud.githubusercontent.com/assets/1716442/26572867/41ad2472-4524-11e7-9a46-673ba4ec0a7f.png)

4. `pck` icon is still shown and syntax highlighting is active.

![screenshot - 30_05_2017 10_32_03](https://cloud.githubusercontent.com/assets/1716442/26572929/79909f36-4524-11e7-8afb-835682d9e562.png)

My apologies to all for creating such a mess. 

@robertohuertasm would you be so kind to close the issue in `vscode`?

**Comment by JimiC** [comment] 2017-05-30 07:47
Just for future reference. If `pck` extension gets added as an extension in `PLSQL` extension the `package` icon is still shown and the manual association in `settings` is redundant.

**Comment by JimiC** [comment] 2017-05-30 07:49
@Danieleeee I guess I now have to make an icon for `pck` and add also `pkh`, `pks`, `pkb` to that. Hopefully, I'll have it done today.

**Comment by robertohuertasm** [comment] 2017-05-30 08:23
@JimiC I tested it myself with `elm` and didn't work, that's why I opened the issue. Let me check it again before closing anything.

**Comment by JimiC** [comment] 2017-05-30 08:34
Could we be testing diff scenarios?

**Comment by robertohuertasm** [comment] 2017-05-30 08:44
The only difference I see is that in your case, `pck` extension is not directly supported by the `PL/SQL` extension while in `elm` it is. 

That's the reason, I think, that this is working for your case. Because you are not having conflicts between `language id` support vs `file extension` support. There's no conflict while in my case it is. You should try to override `pkb` and see what happens.

**Comment by JimiC** [comment] 2017-05-30 09:42
@robertohuertasm I tested with `pkb` with the same result as before.

![screenshot - 30_05_2017 12_41_53](https://cloud.githubusercontent.com/assets/1716442/26577547/64dbb042-4535-11e7-82d3-751fad4dfc97.png)

**Comment by JimiC** [comment] 2017-05-30 09:47
And here is the test with `elm`.

![screenshot - 30_05_2017 12_46_44](https://cloud.githubusercontent.com/assets/1716442/26577754/1a54eeb6-4536-11e7-8875-61419ed17b04.png)

**Comment by robertohuertasm** [comment] 2017-05-30 09:48
Let me check it again... I'm in awe!

**Comment by robertohuertasm** [comment] 2017-05-30 10:21
This has to be investigated.

I was using the `elixir` icon in order to see if I could override the `elm` icon and as you can see it doesn't work:
![image](https://cloud.githubusercontent.com/assets/696981/26578113/e4ab5bb2-452e-11e7-8c77-b82e5cc679a4.png)

Surprisingly, any other seems to be working:
![image](https://cloud.githubusercontent.com/assets/696981/26578005/96a67ee2-452e-11e7-8c75-5e2488a78f22.png)

After a little bit digging I've found that the issue seems to be happening when you try to use an icon which is also defined in the `language id` section:

![image](https://cloud.githubusercontent.com/assets/696981/26578915/051d5870-4532-11e7-9127-f9ed8579789e.png)

As you can see, no matter what the `language id` is. Once it's declared, it will invalidate the `file extension` association.

![image](https://cloud.githubusercontent.com/assets/696981/26578983/47f57b00-4532-11e7-929d-7a85ff7b3bdf.png)

See that `elm` file extension is associated to `elixir` icon which it's also declared to be used by a `language id` association.

I'll change the title and the description of the issue in vscode`s repo.

//cc: @aeschli

**Comment by JimiC** [comment] 2017-05-30 10:26
> the issue seems to be happening when you try to use an icon which is also defined in the language id section

That's the diff scenario.

**Comment by robertohuertasm** [comment] 2017-05-30 10:30
Of course, if we were obtaining different results  we must have been doing something different 😛 

Hopefully, this has been useful to narrow this bug/strange behavior.

**Comment by JimiC** [comment] 2017-05-30 10:32
@Danieleeee Are you ok with this?

![screenshot - 30_05_2017 13_30_42](https://cloud.githubusercontent.com/assets/1716442/26579403/5897aba4-453c-11e7-8538-69f07022fe83.png)

**Comment by Danieleeee** [comment] 2017-05-30 10:53
If possible, I would make a correction.
Ok foo.1.sql and foo.4.pck.
But file.pkh and .pkb should be different from file.pck, they rapresent Header and Body of the package (.pck).
If possible I would enter a 'H' (Header) and 'B' (Body) in the icon.
Idem for file.pks (Spec), similar file.pkh, I will insert an 'S'.

Thanks

**Comment by JimiC** [comment] 2017-05-30 10:59
@robertohuertasm @jens1o Should we expand further the icon differentiation? Personally, I'm against it for the moment.

**Comment by robertohuertasm** [comment] 2017-05-30 11:15
I'll be open to the differentiation given that it makes sense and we're already at it. But if you have a strong opinion about this I'd like to hear it and consider all points of view.

**Comment by JimiC** [comment] 2017-05-30 13:04
My reasoning is that we are introducing 4 more icons which are all related to `PLSQL`. I think it's an overkill. Not to mention that artistically I don't like the idea of adding letter icons. An alternative would be to differentiate the coloring of the `sql` icon but then again I'm not sure what complications this will create with other `sql` like languages.

**Comment by jens1o** [comment] 2017-05-30 14:30
To be honest: I do not care, because I do not use `vscode` for this.

As long as the file is official, I do not see any reason why we shouldn't do that. This format sounds to me like it isn't official...

**Comment by Danieleeee** [comment] 2017-05-30 14:49
You can see more here:
[file extension info](https://www.reviversoft.com/file-extensions/pkh)

**Comment by JimiC** [comment] 2017-05-30 15:15
@jens1o `pck`, `pks`, `pkh`, `pkb` are all official `PL/SQL` files.

**Comment by jens1o** [comment] 2017-05-30 15:32
Okay, then I think we can implement them.

**Comment by JimiC** [comment] 2017-05-30 15:35
@jens1o You are missing the point `pks`, `pkh`, `pkb` are files that produce `pck`. My point is that all should have the same icon hence @Danieleeee wants a diff icon for each.

**Comment by robertohuertasm** [comment] 2017-05-30 15:57
If I understand this correctly `pks`, `pkh` and `pkb` are all different parts of a `pck`. I personally like the idea of having different colors for each one.

**Comment by JimiC** [comment] 2017-05-30 15:59
@robertohuertasm Yeap that's it. You do realize that you make my life difficult (joking). Maybe I consider changing the color of the package icon. This way we'll avoid any future coloring conflicts with `sql` languages.

**Comment by robertohuertasm** [comment] 2017-05-30 16:04
You know @JimiC, that's what colleagues exist for! 😂

**Comment by JimiC** [comment] 2017-05-30 16:09
True... SO true. 😄

**Comment by JimiC** [comment] 2017-05-31 11:29
So I came up with another idea to make my life easier.

How about this?

![screenshot - 31_05_2017 14_27_49](https://cloud.githubusercontent.com/assets/1716442/26630016/9334e354-460d-11e7-9703-2eb3220ca845.png)

**Comment by jens1o** [comment] 2017-05-31 11:55
I'm fine with it.

**Comment by robertohuertasm** [comment] 2017-05-31 12:09
Altougth I think that full color makes them easier to be spotted because you don't have to look at the color distribution but only the general color stain,   I also like this idea of using the red color position to make the mental association with `body` and `header`. 👍

**Closed** 2017-06-02 11:21 UTC
Labels: file icons
