### ISSUE TITLE
vscode-icons causes restart loop with NxWorkspace projects

### ISSUE THREAD

**Issue by eduardoRoth** [vscode-icons/vscode-icons#1939] opened 2019-04-03 20:54 UTC
- [X] I'm sure this issue is not a _duplicate_.

vscode-icons causes NxWorkspace projects to keep reloading.

1. Create a new Nx Workspace (`create-nx-workspace app-name`)
2. Choose "fullstack application"
3. Open it
4. VS Code will keep refreshing itself

Remove `package.json` (or just change it's extension) and issue will disappear.

**Comment by eduardoRoth** [comment] 2019-04-03 21:08
Only happens if you have `vsicons.projectDetection.autoReload` enabled.

**Comment by JimiC** [comment] 2019-04-04 09:52
Duplicate of #1925

**Closed by JimiC** 2019-04-04 09:52 UTC
Labels: bug
