### ISSUE TITLE
TypeError when detecting Angular projects

### ISSUE THREAD

**Issue by davidcie** [vscode-icons/vscode-icons#1461] opened 2018-02-14 20:29 UTC
- [x] I'm sure this issue is not a _duplicate_.

While working on another extension I came across what looks like a missing null check:

    C:\Program Files\Microsoft VS Code\Code.exe --debugBrkPluginHost=46018 --debugId=ce13716a-c56d-46f7-9eb5-d6813e7119af --extensionDevelopmentPath=C:\Users\Dawid\GitHub\vscode-tslint-vue\tslint 
    vscode-icons is active!
    WARNING: Promise with no error callback:3

    Object
    TypeError: path must be a string or Buffer
        at Object.fs.openSync (fs.js:584:18)
        at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
        at Object.fs.readFileSync (fs.js:491:33)
        at Object.exports.wrapFsWithAsar.fs.readFileSync (ELECTRON_ASAR.js:505:29)
        at __dirname.getProjectInfo.results.some.result (C:\Users\Dawid\.vscode\extensions\robertohuertasm.vscode-icons-7.19.0\out\src\init\projectAutoDetection.js:38:32)
        at Array.some (native)
        at Function.getProjectInfo (C:\Users\Dawid\.vscode\extensions\robertohuertasm.vscode-icons-7.19.0\out\src\init\projectAutoDetection.js:37:17)
        at detectAngular (C:\Users\Dawid\.vscode\extensions\robertohuertasm.vscode-icons-7.19.0\out\src\index.js:29:69)
        at projectAutoDetection_1.ProjectAutoDetection.detectProject.then.results (C:\Users\Dawid\.vscode\extensions\robertohuertasm.vscode-icons-7.19.0\out\src\index.js:19:118)
        at Object.g [as _notify] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:68:868)
    vscode-icons is active!
    Congratulations, the extension is working!
    [prograhammer.tslint-vue] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for 'tslint.autoFixOnSave', provide the URI of a resource or 'null' for any resource.

**Comment by robertohuertasm** [comment] 2018-02-14 20:50
Thanks for reporting this @davidcie. We'll look into it.

**Comment by JimiC** [comment] 2018-02-15 15:47
@davidcie Can you share which extension you're using that had that result? You see, this error indicates that our extension detected a `package.json` but `vscode` returned no path to that file, which is kinda strange.

**Comment by JimiC** [comment] 2018-02-15 17:04
Update: Assuming that the project used is https://github.com/prograhammer/vscode-tslint-vue, I managed to see the error in question, when trying to debug the `tslint` sub project. The big BUT in this case is that this error appears only if you haven't first run `npm install`. So, I don't think that's an issue with our extension per say. After performing `npm i` I was presented with another type of errors but unrelated to our extension.

**Comment by JimiC** [comment] 2018-02-15 17:50
Although this an extreme case, and it's presented only when debugging, I managed to figure out what is actually happening. 

Dev stuff follows.

The cause is the mishandling of the `findFiles` rejection. We actually are returning the error as a result which then gets passed into the `getProjectInfo` function.
A PR that fixes this follows.

**Comment by davidcie** [comment] 2018-02-19 08:15
Coming back online after the weekend I see you have already managed to nail it down. Thanks!

**Comment by JimiC** [comment] 2018-02-20 14:45
I'm reopening this issue as I'm seeing the same error when debugging and the `extensionHost` window has no project loaded.

Will work on it asap.

**Comment by JimiC** [comment] 2018-02-20 15:25
Closing. Funny as it may be, after I cleared my cache and recompiled the extension, the issue didn't occur anymore.

**Closed by JimiC** 2018-02-20 15:25 UTC
Labels: bug, confirmed
